### ISSUE TITLE
You can add Rodinia benchmark

### ISSUE THREAD

**Issue by chunhualiao** [gleisonsdm/OpenMP_benchmarks#1]
You can add Rodinia benchmark

**Comment by gleisonsdm** [comment]
It is at:
[https://github.com/gleisonsdm/OpenMP_benchmarks/tree/master/DawnCC_BENCHS/rodinia](https://github.com/gleisonsdm/OpenMP_benchmarks/tree/master/DawnCC_BENCHS/rodinia)
