### ISSUE TITLE
bots, not boots

### ISSUE THREAD

**Issue by chunhualiao** [gleisonsdm/OpenMP_benchmarks#2]
Please double check /correct the name of the benchmark @gleisonsdm

**Comment by gleisonsdm** [comment]
The name is correct now, it is at:
[https://github.com/gleisonsdm/OpenMP_benchmarks/tree/master/DawnCC_BENCHS/bots](https://github.com/gleisonsdm/OpenMP_benchmarks/tree/master/DawnCC_BENCHS/bots)
