### ISSUE TITLE
Survey Question on the For loop in source file other-nearest_gpu.c line 191

### ISSUE THREAD

**Issue by quazirafi** [gleisonsdm/OpenMP_benchmarks#3]
Hello Sir/ Mam,
We are from a research group at Iowa State University, USA. We want to do a survey on Github developers on the methods they used for paralleling their code. To do the survey, We want to ask three questions about this for loop:

Can you briefly explain the purpose of using pragma for this case? If the pragma contained reduction and private clauses, can you briefly mention the purposes of variables in those clauses?

How much confidence do you have about the correctness of this implementation? You can choose from 1-5 with 1 as the lowest confidence score and 5 as the highest confidence score.

(Optional) Do you actually run (interpret the code with compilation and pass input/get output) the code and see the optimization of parallelization? Yes/No

If yes, can you provide the information of what are the input and expected output of this program (the input that caused the program to run through this for-loop).

The for loop is from line 191 of file 
https://github.com/gleisonsdm/OpenMP_benchmarks/blob/master/DawnCC_BENCHS/UniBenchV2/mgBench/other-nearest/src/other-nearest_gpu.c

Here is a part of the code:

for (i = 0; i < s; i++)
{
  for (j = 0; j < s; j++)
  {
    for (m = j + 1; m < s; m++)
    {
      if (selected[(i * s) + j].value > selected[(i * s) + m].value)
      {
        sel_points aux;
        aux = selected[(i * s) + j];
        selected[(i * s) + j] = selected[(i * s) + m];
        selected[(i * s) + m] = aux;
      }

    }

  }

}

**Comment by gleisonsdm** [comment]
Hello, 

1- Can you briefly explain the purpose of using pragma for this case? If the pragma contained reduction and private clauses, can you briefly mention the purposes of variables in those clauses?
This code was parallelized by DawnCC, a compiler able to insert OpenMP and OpenACC directives without human intervention for heterogeneous architectures (such as sending the code to GPUs). It did not consider a cost model to estimate profitability for the code snippet produced.

2- How much confidence do you have about the correctness of this implementation? You can choose from 1-5 with 1 as the lowest confidence score and 5 as the highest confidence score.
5 - The code was executed (a few years age) and it has produced the same output as the sequential program. Notice that
it does not contain the directive "for", meaning that the data offload was tested, but it seems to me that the code will execute
sequentially in the GPU.

Regards

**Comment by quazirafi** [comment]
Thank you so much for the response. I am closing this issue.
