### ISSUE TITLE
Survey Question on the For loop in source file. https:/github.com/gleisonsdm/OpenMP_benchmarks/blob/master/Original/UniBenchV2/Parboil/stencil/src/kernels.c line 19

### ISSUE THREAD

**Issue by quazirafi** [gleisonsdm/OpenMP_benchmarks#4]
Hello Sir/ Madam
We are from a research group at Iowa State University, USA. We want to do a survey on Github developers on the methods they used for paralleling their code. To do the survey, We want to ask three questions about this for loop:

Can you briefly explain the purpose of using pragma for this case? If the pragma contained reduction and private clauses, can you briefly mention the purposes of variables in those clauses?

How much confidence do you have about the correctness of this implementation? You can choose from 1-5 with 1 as the lowest confidence score and 5 as the highest confidence score.

(Optional) Do you actually run (interpret the code with compilation and pass input/get output) the code and see the optimization of parallelization? Yes/No

If yes, can you provide the information of what are the input and expected output of this program (the input that caused the program to run through this for-loop).
The for loop is from line 19 of file https:/github.com/gleisonsdm/OpenMP_benchmarks/blob/master/Original/UniBenchV2/Parboil/stencil/src/kernels.c
Here is a part of the code:

#pragma omp parallel for
  for (k = 1; k < nz - 1; k++) {
    for (j = 1; j < ny - 1; j++) {
      for (i = 1; i < nx - 1; i++) {
        Anext[Index3D(nx, ny, i, j, k)] = (A0[Index3D(nx, ny, i, j, k + 1)] +
                                           A0[Index3D(nx, ny, i, j, k - 1)] +
                                           A0[Index3D(nx, ny, i, j + 1, k)] +
                                           A0[Index3D(nx, ny, i, j - 1, k)] +
                                           A0[Index3D(nx, ny, i + 1, j, k)] +
                                           A0[Index3D(nx, ny, i - 1, j, k)]) *
                                              c1 -
                                          A0[Index3D(nx, ny, i, j, k)] * c0;
      }
    }
  }
}

**Comment by gleisonsdm** [comment]
Hello, 

1- Can you briefly explain the purpose of using pragma for this case? If the pragma contained reduction and private clauses, can you briefly mention the purposes of variables in those clauses?
Hi, it parallelizes a code snippet where each thread writtes on its own position in the array. Notice that "A0" is just read inside the loop.

2- How much confidence do you have about the correctness of this implementation? You can choose from 1-5 with 1 as the lowest confidence score and 5 as the highest confidence score.
5 - As the code does not have any race condition, plus was produced by an expert.

Regards

**Comment by quazirafi** [comment]
Thank you so much for the response. I am closing this issue.
